apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "rfjs-service.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "rfjs-service.fullname" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "rfjs-service.fullname" . }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "rfjs-service.fullname" . }}
    spec:
      containers:
        - name: {{ include "rfjs-service.fullname" . }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.containerPort }}
              name: http
          env:
            {{- range $k, $v := .Values.env }}
            - name: {{ $k }}
              value: {{ $v | quote }}
            {{- end }}

          {{- if and .Values.secrets.existingSecretName .Values.secrets.useEnvFrom }}
          envFrom:
            - secretRef:
                name: {{ .Values.secrets.existingSecretName }}
          {{- end }}

          readinessProbe:
            httpGet:
              path: /health
              port: {{ .Values.containerPort }}
            initialDelaySeconds: 5
            periodSeconds: 10

          livenessProbe:
            httpGet:
              path: /health
              port: {{ .Values.containerPort }}
            initialDelaySeconds: 15
            periodSeconds: 20

          resources:
            {{- toYaml .Values.resources | nindent 12 }}
