# {{- if .Values.secretEnv }}
# apiVersion: v1
# kind: Secret
# metadata:
#   name: {{ include "rfjs-service.fullname" . }}-env
# type: Opaque
# stringData:
#   {{- range $k, $v := .Values.secretEnv }}
#   {{ $k }}: {{ $v | quote }}
#   {{- end }}
# {{- end }}
